// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqszmmvxwuwhybvusoac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxc3ptbXZ4d3V3aHlidnVzb2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjcyODgsImV4cCI6MjA2MDQ0MzI4OH0.y6HQ554Vlj2X6GFBIJCCWIKufoKQBvsXj-VQ0UaI-Cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);